language: node_js
node_js:
  - "iojs"
  - "7"

# before_script:
#   - npm install  -g eslint # or install only eslint plugins needed
  
#  script:
#   - npm run eslint # eslint  in scripts of package.json
  
#  cache:
#   apt: true
#   directories:
#     - node_module  
